name: Go

on:
    push:
    pull_request_target:

jobs:
    gobuild:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/setup-go@v3
                with:
                    go-version: 1.21
            -   uses: actions/checkout@v3
            -   name: go build
                run: go build -v ./...

    gotest:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/setup-go@v3
                with:
                    go-version: 1.21
            -   uses: actions/checkout@v3
            -   name: go build
                run: go test -v ./...

    golangci:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/setup-go@v3
                with:
                    go-version: 1.21
            -   uses: actions/checkout@v3
            -   name: golangci-lint
                uses: golangci/golangci-lint-action@v3
                with:
                    version: latest
